import { Profile } from './types';

export const PROFILES: Profile[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    age: 26,
    gender: 'Female',
    occupation: 'Software Engineer at Google',
    location: 'Bangalore, India',
    community: 'Brahmin',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUY9DUJaTLM0V9UjdiNwhcfjTJMWNGEiFZ1VVB5lPbHTMJcvG_0GdHY9KeBPJAwbntssV2PKPE162s5M-fDU-bRtapSvBR-pUF6mXGaf2b7knGZ5Jdsj9qCkOHrMlXFSyIgHHqkqzTsaoV-XJFAw4iF2i7ds1vqgGF4_Q54vLExBle9UVcyrhcXQbElRmH3y1Fa2XZqVJjE4Wxcw44ueScsZkXeOTMQVjY7oR0IffxRS3SJ7TWUiGdKKt18HfysRxJq2ne-scNhL-e',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBUY9DUJaTLM0V9UjdiNwhcfjTJMWNGEiFZ1VVB5lPbHTMJcvG_0GdHY9KeBPJAwbntssV2PKPE162s5M-fDU-bRtapSvBR-pUF6mXGaf2b7knGZ5Jdsj9qCkOHrMlXFSyIgHHqkqzTsaoV-XJFAw4iF2i7ds1vqgGF4_Q54vLExBle9UVcyrhcXQbElRmH3y1Fa2XZqVJjE4Wxcw44ueScsZkXeOTMQVjY7oR0IffxRS3SJ7TWUiGdKKt18HfysRxJq2ne-scNhL-e',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=640',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=640',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=640',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=640'
    ],
    verified: true,
    about: 'I am a balanced individual who values traditional family roots while embracing modern professional growth. Currently working as a Senior SDE at a global fintech firm, I enjoy travel, classical music, and weekend culinary experiments. Seeking a companion who is ambitious yet grounded.',
    height: '5\'6" (167 cm)',
    motherTongue: 'Hindi',
    maritalStatus: 'Never Married',
    education: 'B.Tech, IIT Delhi',
    employer: 'Google',
    income: '₹30L+ annually',
    diet: 'Vegetarian',
    drinkSmoke: 'No / No',
    interests: ['Classical Dance', 'Photography', 'Yoga', 'Trekking'],
    dateOfBirth: '2000-03-15',
    religion: 'Hindu',
    caste: 'Brahmin',
    gotra: 'Kashyap',
    manglik: 'No',
    familyType: 'Nuclear',
    familyStatus: 'Upper Middle Class',
    fatherOccupation: 'Retired Professor, Delhi University',
    motherOccupation: 'Homemaker',
    siblings: '1 Elder Brother (Married)',
    hometown: 'New Delhi, India',
    residencyStatus: 'Indian Citizen',
    horoscope: 'Pisces',
    complexion: 'Fair',
    bodyType: 'Slim',
    disability: 'None',
    educationDetail: 'B.Tech Computer Science, IIT Delhi (2018-2022)',
    additionalDegrees: ['Machine Learning Specialization, Stanford Online'],
    languagesKnown: ['Hindi', 'English', 'Sanskrit']
  },
  {
    id: '2',
    name: 'Arjun Mehta',
    age: 29,
    gender: 'Male',
    occupation: 'Investment Banker',
    location: 'Mumbai, India',
    community: 'Gujarati',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCISLa9MwxVKLVJn3bKcgyXSm9arQzXBJNKuzw-AtnnW0NV8UJqjGrGt9HTwmArtbyL0BDefm5vc57IxwaFfbrEaq4nZYoBM_AlxJ3gKxx-C6jJJ5wSZmoIBqsIeVQtLpU3hS2g4DaEFdqDceq-LgIQV6JwujDCzyzWv82quUpWeGUXSJ6K2jMtzCdtyCCNvk9hbqKkyninfQCI_5tyyVtmT5-gSKU0xv61CKqvJy_rwUIeez-JmYTWKsQDHg6qRjOMzMW17Tok2hTY',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCISLa9MwxVKLVJn3bKcgyXSm9arQzXBJNKuzw-AtnnW0NV8UJqjGrGt9HTwmArtbyL0BDefm5vc57IxwaFfbrEaq4nZYoBM_AlxJ3gKxx-C6jJJ5wSZmoIBqsIeVQtLpU3hS2g4DaEFdqDceq-LgIQV6JwujDCzyzWv82quUpWeGUXSJ6K2jMtzCdtyCCNvk9hbqKkyninfQCI_5tyyVtmT5-gSKU0xv61CKqvJy_rwUIeez-JmYTWKsQDHg6qRjOMzMW17Tok2hTY',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=640',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=640',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=640'
    ],
    verified: false,
    about: 'Driven professional looking for a partner to share life\'s beautiful moments. Love traveling, playing cricket on weekends, and investing in startups.',
    height: '6\'0" (183 cm)',
    motherTongue: 'Gujarati',
    maritalStatus: 'Never Married',
    education: 'MBA, IIM Ahmedabad',
    employer: 'JP Morgan Chase',
    income: '₹45L+ annually',
    diet: 'Eggetarian',
    drinkSmoke: 'Occasionally / No',
    interests: ['Cricket', 'Stock Trading', 'Travel', 'Startups', 'Fine Dining'],
    dateOfBirth: '1997-08-22',
    religion: 'Hindu',
    caste: 'Patel',
    gotra: 'Bharadwaj',
    manglik: 'No',
    familyType: 'Joint',
    familyStatus: 'Rich / Affluent',
    fatherOccupation: 'Business Owner, Textile Industry',
    motherOccupation: 'Homemaker',
    siblings: '1 Younger Sister (Unmarried)',
    hometown: 'Surat, Gujarat',
    residencyStatus: 'Indian Citizen',
    horoscope: 'Leo',
    complexion: 'Wheatish',
    bodyType: 'Athletic',
    disability: 'None',
    educationDetail: 'MBA Finance, IIM Ahmedabad (2020-2022)',
    additionalDegrees: ['B.Com Honours, SRCC Delhi (2015-2018)', 'CFA Level 2'],
    languagesKnown: ['Gujarati', 'Hindi', 'English', 'Marathi']
  },
  {
    id: '3',
    name: 'Ananya Iyer',
    age: 25,
    gender: 'Female',
    occupation: 'Creative Director',
    location: 'Chennai, India',
    community: 'Tamil Brahmin',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBNuK_C5ixobi6JpoQLtOrXHCNCgD9OCZO4YW3Z-nGC5UEi0D7S8o_bpzkCyZPrN88m9QkzQAcBw_Da8pF0gQUAulaTvSGIrSHGZGvizr4RpLAVkokj_1-dLoy9nQpmjD6fFvAyqbUREZbqlyzxh0E0mtYHUc3vBs_pc1dAO44TyVV-q3DjUx3o_WsxDXiEGfASIBoW49Js4dbg1O84hYeIWImCVUwPz5lAJpTka3tWz5iQn2lRU4gzqkgdCi3-y2Po56KCSJffp9i6',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBNuK_C5ixobi6JpoQLtOrXHCNCgD9OCZO4YW3Z-nGC5UEi0D7S8o_bpzkCyZPrN88m9QkzQAcBw_Da8pF0gQUAulaTvSGIrSHGZGvizr4RpLAVkokj_1-dLoy9nQpmjD6fFvAyqbUREZbqlyzxh0E0mtYHUc3vBs_pc1dAO44TyVV-q3DjUx3o_WsxDXiEGfASIBoW49Js4dbg1O84hYeIWImCVUwPz5lAJpTka3tWz5iQn2lRU4gzqkgdCi3-y2Po56KCSJffp9i6',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=640',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=640',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=640',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=640'
    ],
    verified: true,
    about: 'Creative soul with a love for arts and tradition. Currently heading design at a top agency, I find joy in Bharatanatyam, painting, and exploring Tamil heritage sites.',
    height: '5\'5" (165 cm)',
    motherTongue: 'Tamil',
    maritalStatus: 'Never Married',
    education: 'B.Des, NID Ahmedabad',
    employer: 'Leo Burnett',
    income: '₹20L+ annually',
    diet: 'Vegetarian',
    drinkSmoke: 'No / No',
    interests: ['Bharatanatyam', 'Painting', 'Temple Visits', 'Reading', 'UX Design'],
    dateOfBirth: '2001-01-10',
    religion: 'Hindu',
    caste: 'Iyer',
    gotra: 'Vatsa',
    manglik: 'No',
    familyType: 'Nuclear',
    familyStatus: 'Upper Middle Class',
    fatherOccupation: 'Senior Manager, TCS',
    motherOccupation: 'School Principal',
    siblings: 'No Siblings',
    hometown: 'Trichy, Tamil Nadu',
    residencyStatus: 'Indian Citizen',
    horoscope: 'Capricorn',
    complexion: 'Fair',
    bodyType: 'Slim',
    disability: 'None',
    educationDetail: 'B.Des Communication Design, NID Ahmedabad (2019-2023)',
    additionalDegrees: ['Google UX Design Certificate'],
    languagesKnown: ['Tamil', 'English', 'Hindi', 'French (Basic)']
  },
  {
    id: '4',
    name: 'Rohan Das',
    age: 31,
    gender: 'Male',
    occupation: 'Architect & Designer',
    location: 'Kolkata, India',
    community: 'Bengali',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQBbtNIX_DNKtfGq4rN0nnncgT5kxMXf4tzLLTRYWZ1lJZXMOnzUc9tjjA5R8QH-eGmapKvwoHQXRFBVIrLpaU03MT1k0d-7lKCRYYqalvI-6sJGDuaCSa2yu4eKqpAgcOsVNmIIsBPIJrg-AINsooozMQcxc0s-GuyLH4CWAbX4wRmZj-7boqGDpuKHJ_G-bUHrZv8FoDTYWUXZi5SK317S-Bo9YojzHJwzoqxKbRdbwZgP4kOTTHUKuGUOuinH4No2FR8OHUacrC',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDQBbtNIX_DNKtfGq4rN0nnncgT5kxMXf4tzLLTRYWZ1lJZXMOnzUc9tjjA5R8QH-eGmapKvwoHQXRFBVIrLpaU03MT1k0d-7lKCRYYqalvI-6sJGDuaCSa2yu4eKqpAgcOsVNmIIsBPIJrg-AINsooozMQcxc0s-GuyLH4CWAbX4wRmZj-7boqGDpuKHJ_G-bUHrZv8FoDTYWUXZi5SK317S-Bo9YojzHJwzoqxKbRdbwZgP4kOTTHUKuGUOuinH4No2FR8OHUacrC',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=640',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=640',
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=640'
    ],
    verified: false,
    about: 'Passionate about building homes and hoping to build a beautiful life together. Love Rabindra Sangeet, Bengali cuisine, and weekend trips to the Sundarbans.',
    height: '5\'10" (178 cm)',
    motherTongue: 'Bengali',
    maritalStatus: 'Never Married',
    education: 'M.Arch, IIT Kharagpur',
    employer: 'Self-Employed (Das & Partners Studio)',
    income: '₹25L+ annually',
    diet: 'Non-Vegetarian',
    drinkSmoke: 'Occasionally / No',
    interests: ['Rabindra Sangeet', 'Architecture Photography', 'Cooking', 'Cricket', 'Travel'],
    dateOfBirth: '1995-06-20',
    religion: 'Hindu',
    caste: 'Kayastha',
    gotra: 'Shandilya',
    manglik: 'Yes (Remedied)',
    familyType: 'Joint',
    familyStatus: 'Upper Middle Class',
    fatherOccupation: 'Retired Civil Engineer, CPWD',
    motherOccupation: 'Hindi Teacher (Retired)',
    siblings: '2 Elder Sisters (Both Married)',
    hometown: 'Howrah, West Bengal',
    residencyStatus: 'Indian Citizen',
    horoscope: 'Gemini',
    complexion: 'Wheatish',
    bodyType: 'Average',
    disability: 'None',
    educationDetail: 'M.Arch Sustainable Design, IIT Kharagpur (2017-2019)',
    additionalDegrees: ['B.Arch, Jadavpur University (2013-2017)', 'LEED Green Associate'],
    languagesKnown: ['Bengali', 'Hindi', 'English']
  }
];
